train : 
  plot :
    wkt5271g : 
      slurm_id: 800704
      description: "e01"
      eval: vgbndhco
    sqsvm93f : 
      slurm_id: 800708
      description: "e02"
      eval: vgbndhco
    vk6ntaya : 
      slurm_id: 800722
      description: "e03"
      eval: vgbndhco
    tleilmsh : 
      slurm_id: 800825
      description: "e04"
      eval: vgbndhco
    cr067tz5 : 
      slurm_id: 800885 
      description: "e05"
      eval: vgbndhco
