train : 
  plot :
    g7pzmqx3 : 
      slurm_id: 999606
      description: "e13"
      eval: vgbndhco
#    f9074xu6 : 
#      slurm_id: 999608
#      description: "e14"
#      eval: vgbndhco
    v74kw3m5 : 
      slurm_id: 1006247
      description: "e13cont"
      eval: vgbndhco
#    cqc8wr39 : 
#      slurm_id: 1004108
#      description: "e16"
#      eval: vgbndhco
#    siq6bwu9 : 
#      slurm_id: 1005025
#      description: "e16a"
#      eval: vgbndhco
